name: AWS Deploy Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        ls -al
        python -m venv venv
        source venv/bin/activate
        cd TestApp
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        export REQUIRED_SETTING="DEV"
        cd TestApp
        chmod +x test.sh
        ./test.sh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: cd TestApp && docker build -t assesment:latest .
    
    - name: Check Docker image
      run: docker images

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag Docker image
      run: docker tag assesment:latest 010526269666.dkr.ecr.us-east-1.amazonaws.com/takehomeassesment:${{ github.sha }}
    
    - name: Push Docker image to Amazon ECR
      run: docker push 010526269666.dkr.ecr.us-east-1.amazonaws.com/takehomeassesment:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
          working_dir: 'cdk-deployment'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          DOCKER_IMAGE_TAG: ${{ github.sha }}

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'TakeHomeAssesmentStack'
          cdk_args: '--require-approval never'
          actions_comment: false
          working_dir: 'cdk-deployment'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKER_IMAGE_TAG: ${{ github.sha }}
          AWS_DEFAULT_REGION: 'us-east-1'
          
