name: AWS Deploy Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        ls -al
        python -m venv venv
        source venv/bin/activate
        cd TestApp
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        export REQUIRED_SETTING="DEV"
        cd TestApp
        chmod +x test.sh
        ./test.sh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: cd TestApp && docker build -t assesment:latest .
    
    - name: Check Docker image
      run: docker images

